shop_id: tshop00036263
shop_pass: 14pwdzm1
site_id: tsite00032286
site_pass: z1sxyvbq
host: pt01.mul-pay.jp
token_member_id: 1
token: 1

remittance:
  shop_id: rshop00000169
  shop_pass: oMZ2K9WH
  host: test-remittance.gmopg.jp
